export type AdminNavItem = {
  label: string
  href: string
  section: string
  keywords?: string[]
}

/** Shared admin navigation for sidebar + Cmd-K */
export const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  { label: "Dashboard", href: "/admin", section: "CORE", keywords: ["home", "overview"] },
  { label: "Manage Users", href: "/admin/users", section: "CORE", keywords: ["employees", "staff"] },
  { label: "Job Postings", href: "/admin/jobs", section: "RECRUITMENT" },
  { label: "Applications", href: "/admin/applications", section: "RECRUITMENT" },
  { label: "Job Analytics", href: "/admin/analytics", section: "RECRUITMENT" },
  { label: "Communications", href: "/admin/communications", section: "RECRUITMENT" },
  { label: "Leave Requests", href: "/admin/leave", section: "EMPLOYEE MANAGEMENT" },
  { label: "Attendance Tracker", href: "/admin/attendance", section: "EMPLOYEE MANAGEMENT" },
  { label: "Allocations", href: "/admin/allocations", section: "EMPLOYEE MANAGEMENT" },
  { label: "Payroll Management", href: "/admin/payroll", section: "EMPLOYEE MANAGEMENT" },
  { label: "Meetings", href: "/admin/meetings", section: "EMPLOYEE MANAGEMENT" },
  { label: "Add Inventory", href: "/admin/stock/add-inventory", section: "INVENTORY MANAGER", keywords: ["products", "stock"] },
  { label: "Warehouse Management", href: "/admin/stock/wms", section: "INVENTORY MANAGER" },
  { label: "Stock Checks", href: "/admin/stock/stock-check", section: "INVENTORY MANAGER" },
  { label: "Sales", href: "/admin/stock/sales", section: "INVENTORY MANAGER" },
  { label: "Quotations", href: "/admin/stock/quotations", section: "INVENTORY MANAGER", keywords: ["quotes"] },
  { label: "New Quotation", href: "/admin/stock/quotations?action=new", section: "INVENTORY MANAGER", keywords: ["create quote"] },
  { label: "Tenders", href: "/admin/stock/tender", section: "INVENTORY MANAGER" },
  { label: "Services", href: "/admin/stock/services", section: "INVENTORY MANAGER" },
  { label: "Invoices", href: "/admin/stock/invoices", section: "INVENTORY MANAGER", keywords: ["billing"] },
  { label: "Credit Notes", href: "/admin/stock/credit-notes", section: "INVENTORY MANAGER" },
  { label: "Dispatch", href: "/admin/stock/dispatch", section: "INVENTORY MANAGER" },
  { label: "eTIMS Posts", href: "/admin/accounts/posts", section: "ACCOUNTS", keywords: ["kra", "tax"] },
  { label: "Payments", href: "/admin/accounts/payments", section: "ACCOUNTS" },
  { label: "Debts", href: "/admin/accounts/debts", section: "ACCOUNTS" },
  { label: "Expenses", href: "/admin/accounts/expenses", section: "ACCOUNTS" },
  { label: "Clients Hub", href: "/admin/clients", section: "CLIENTS", keywords: ["customers", "crm"] },
  { label: "Client CRM", href: "/admin/clients/clients-list", section: "CLIENTS", keywords: ["customers", "crm", "contacts", "groups", "directory", "telesales", "calls"] },
  { label: "Sales Reports", href: "/admin/sales-reports", section: "CLIENTS", keywords: ["sales rep", "field", "quotes", "approval", "visits"] },
  { label: "Field Reports", href: "/admin/field-management/reports", section: "FIELD MANAGEMENT", keywords: ["visits", "sales report", "outcome", "planner"] },
  { label: "Planner", href: "/admin/field-management/planner", section: "FIELD MANAGEMENT", keywords: ["sales planner", "approve"] },
  { label: "Performance", href: "/admin/field-management/performance", section: "FIELD MANAGEMENT", keywords: ["sales target", "quota", "reps"] },
  { label: "Installed Machines", href: "/admin/clients/installed-machines", section: "CLIENTS", keywords: ["machines", "service", "tickets"] },
  { label: "Complaints", href: "/admin/clients/complaints", section: "CLIENTS" },
  { label: "Bulk SMS", href: "/admin/clients/bulk-sms", section: "CLIENTS" },
  { label: "Fleet Tracker", href: "/admin/fleet", section: "FLEET", keywords: ["vehicles"] },
  { label: "Alerts & Notifications", href: "/admin/alerts", section: "SYSTEM", keywords: ["inbox", "bell"] },
  { label: "KPIs", href: "/admin/kpis", section: "PERFORMANCE" },
  { label: "360 Feedback", href: "/admin/feedback-360", section: "PERFORMANCE" },
  { label: "Reports Hub", href: "/admin/reports", section: "PERFORMANCE" },
  { label: "Company Settings", href: "/admin/settings/company", section: "SYSTEM" },
  { label: "System Settings", href: "/admin/settings/system", section: "SYSTEM" },
  { label: "Email Settings", href: "/admin/settings/system/email", section: "SYSTEM", keywords: ["smtp", "mail", "domain"] },
  { label: "Page Access", href: "/admin/settings/system/page-access", section: "SYSTEM" },
  { label: "Contracts", href: "/admin/contracts", section: "EMPLOYEE MANAGEMENT" },
  { label: "Stamps", href: "/admin/stamps", section: "SYSTEM" },
]
